return {
	Classes = {
		WrapTarget = {
			CallbackOverloads = {},
			Callbacks = {},
			Events = {},
			FunctionOverloads = {},
			Functions = {},
			ModifierFlags = {},
			Modifiers = "",
			Name = "WrapTarget",
			Properties = {
				Color = {
					ModifierFlags = {
						NotReplicated = true,
						NotScriptable = true,
					},
					Name = "Color",
					Raw = "Color3 {🛠️AvatarAppearance} [NotReplicated] [NotScriptable]",
					Type = "Color3",
				},
				DebugMode = {
					ModifierFlags = {
						NotReplicated = true,
						NotScriptable = true,
					},
					Name = "DebugMode",
					Raw = "Enum.WrapTargetDebugMode {🛠️AvatarAppearance} [NotReplicated] [NotScriptable]",
					Type = "Enum.WrapTargetDebugMode",
				},
				Stiffness = {
					ModifierFlags = {},
					Name = "Stiffness",
					Raw = "number {🛠️AvatarAppearance} {✏️Plugin}",
					Type = "number",
				},
			},
			Super = "BaseWrap",
		},
		WrapTextureTransfer = {
			CallbackOverloads = {},
			Callbacks = {},
			Events = {},
			FunctionOverloads = {},
			Functions = {},
			ModifierFlags = {},
			Modifiers = "",
			Name = "WrapTextureTransfer",
			Properties = {
				ReferenceCageMeshContent = {
					ModifierFlags = {},
					Name = "ReferenceCageMeshContent",
					Raw = "Content {🛠️AvatarAppearance}",
					Type = "Content",
				},
				UVMaxBound = {
					ModifierFlags = {},
					Name = "UVMaxBound",
					Raw = "Vector2 {🛠️AvatarAppearance}",
					Type = "Vector2",
				},
				UVMinBound = {
					ModifierFlags = {},
					Name = "UVMinBound",
					Raw = "Vector2 {🛠️AvatarAppearance}",
					Type = "Vector2",
				},
			},
			Super = "Instance",
		},
	},
}