from __future__ import annotations

from typing import Dict, Any


OPCODE_NAMES = {
    0: "MOVE",
    1: "LOADK",
    2: "LOADBOOL",
    3: "LOADNIL",
    4: "GETUPVAL",
    5: "GETGLOBAL",
    6: "GETTABLE",
    7: "SETGLOBAL",
    8: "SETUPVAL",
    9: "SETTABLE",
    10: "NEWTABLE",
    11: "SELF",
    12: "ADD",
    13: "SUB",
    14: "MUL",
    15: "DIV",
    16: "MOD",
    17: "POW",
    18: "UNM",
    19: "NOT",
    20: "LEN",
    21: "CONCAT",
    22: "JMP",
    23: "EQ",
    24: "LT",
    25: "LE",
    26: "TEST",
    27: "TESTSET",
    28: "CALL",
    29: "TAILCALL",
    30: "RETURN",
    31: "FORLOOP",
    32: "FORPREP",
    33: "TFORLOOP",
    34: "SETLIST",
    35: "CLOSE",
    36: "CLOSURE",
    37: "VARARG",
}
